import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PublicLayout from "@/components/layouts/publicLayout";
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark">
        <ReduxProvider>
          <PublicLayout>{children}</PublicLayout>
        </ReduxProvider>
      </body>
    </html>
  );
}
